In [1]:
import numpy as np

In [2]:
def generar_datos_ventas(productos, tiendas, dias):
    # Genera datos de ventas aleatorias para el número de productos, tiendas y días especificados

    return np.random.randint(0, 101, (productos, tiendas, dias))

def calcular_totales_ventas_por_producto(datos):
    # Calcula el total de ventas por producto a lo largo de la semana
    return np.sum(datos, axis=(1, 2))

def calcular_totales_ventas_por_tienda(datos):
    # Calcula el total de ventas por tienda a lo largo de la semana
    return np.sum(datos, axis=(0, 2))

def calcular_promedio_ventas_por_producto(datos):
    # Calcula el promedio de ventas por producto por día
    return np.mean(datos, axis=(1, 2))

def calcular_promedio_ventas_por_tienda(datos):
    # Calcula el promedio de ventas por tienda por día
    return np.mean(datos, axis=(0, 2))

def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    # Encuentra el producto con mayor y menor ventas totales en la semana
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas

In [3]:
productos = 10
tiendas = 5
dias = 7

# Genera los datos de ventas
datos = generar_datos_ventas(productos, tiendas, dias)

print("datos: ", datos)
# Calcula los totales y promedios
totales_por_producto = calcular_totales_ventas_por_producto(datos)
totales_por_tienda = calcular_totales_ventas_por_tienda(datos)
promedio_por_producto = calcular_promedio_ventas_por_producto(datos)
promedio_por_tienda = calcular_promedio_ventas_por_tienda(datos)

# Encuentra el producto y la tienda con mayor y menor ventas
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)

# Imprime los resultados
print("Total de ventas por producto a lo largo de la semana:", totales_por_producto)
print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)
print("Promedio de ventas por producto por día:", promedio_por_producto)
print("Promedio de ventas por tienda por día:", promedio_por_tienda)
print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
print(f"Producto con menor ventas: Producto {producto_menor_ventas}")
print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")


datos:  [[[ 42  55  80  71  89  34   9]
  [ 91  23  87  28  52  41  30]
  [ 96  98  65  81  75  91  23]
  [ 22  79  50  51  68  44  84]
  [ 81  25  77  24  71  43  67]]

 [[  9  60  76  99  48   0  88]
  [ 84  35  73  43  84  72  53]
  [ 35  82   2   8  19  27  15]
  [ 52  29  63  16  34  58  17]
  [ 85  98  28  53  46  62  27]]

 [[ 45  13  49  44  34  35  55]
  [ 86   8  96  95   9  33  36]
  [100  49  92   1  88  23  29]
  [ 23  15  14  51  87  60   1]
  [ 79  99  30  56   6  88  73]]

 [[ 97  27  55  28  59   3  63]
  [ 11  90  60  29  65  42  83]
  [ 98  94  28  33  20  47  55]
  [ 26  78  29  36  39   8  17]
  [ 32  60  97  56  81  71  49]]

 [[ 57  65  60  89  27  97  59]
  [ 61  53  16  85  87 100  47]
  [  5  76  49  19   7  49  57]
  [ 45  46  49   0  30  50  88]
  [ 61   5  64  48  56  72  58]]

 [[ 89 100  40  86  26  22   1]
  [ 97  19  27  36   6  26  26]
  [ 23  20  30  76  61  86  75]
  [ 78   2  67  52  29  12  22]
  [ 49  76  78  57   0  91  21]]

 [[ 13   8   5  94  